name: Deploy VitePress Site

# 触发条件：推送到 main 分支时触发
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]  

# 支持手动在工作流上触发
  workflow_dispatch:

# 权限设置
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 必要，用于获取完整的Git历史

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: Verify pnpm
        run: pnpm --version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check script existence
        run: |
          # 检查是否存在 docs:build 命令
          if ! grep -q '"docs:build":' package.json; then
            echo "Error: 未找到 docs:build 命令"
            exit 1
          fi

      - name: Build VitePress site
        run: pnpm run docs:build  # 使用自定义的构建命令

      - name: Verify build output
        run: |
          echo "构建目录内容："
          ls -la docs/.vitepress/dist  # 确认构建产物是否存在
          echo "检查样式文件："
          ls -la docs/.vitepress/dist/assets  # 确认样式文件是否存在

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/.vitepress/dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
