name: Deploy VitePress Site

# 触发条件：推送到 main 分支时触发
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [main]  

# 支持手动在工作流上触发
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # 必要，用于获取完整的Git历史

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check script existence
        run: |
          # 检查是否存在 docs:build 命令
          if ! grep -q '"docs:build":' package.json; then
            echo "Error: 未找到 docs:build 命令"
            exit 1
          fi

      - name: Build VitePress site
        run: pnpm run docs:build  # 使用自定义的构建命令

      - name: Verify build output
        run: |
          echo "构建目录内容："
          ls -la docs/.vitepress/dist  # 确认构建产物是否存在

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vitepress/dist
          commit_message: 'docs: update site (${{ github.sha }})'
